server:
  port: 8206
spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #≈‰÷√Nacosµÿ÷∑
management:
  endpoints:
    web:
      exposure:
        include: '*'