server:
  port: 8555
spring:
  application:
    name: nacos-server-feign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    max-connections-per-route: 50
    max-connections: 200
  hystrix:
    enabled: true